published:
  - app:
      category: life
      application: weather
      name: 教室安排
      weichaturl: /pages/classroomManage/classroomManage
      serverurl: /service/weather
      icon: /images/GIS-TL_jieshuidian.png
      code: 10
  - app:
      category: java
      application: java
      name: java
      weichaturl: /pages/index/index
      serverurl: /service/weather
      icon: /images/GIS-TL_shuibiaoxiang.png
      code: 11
  - app:
        category: java
        application: java
        name: 我的课表
        weichaturl: /pages/myCourseList/myCourseList
        serverurl: /service/weather
        icon: /images/GIS-TL_xiaofangbiao.png
        code: 12
  - app:
        category: java
        application: java
        name: 教室信息
        weichaturl: /pages/labList/labList
        serverurl: /service/weather
        icon: /images/GIS-TL_liuliangkongzhifa.png
        code: 13
  - app:
        category: java
        application: java
        name: 实验员
        weichaturl: /pages/experimenterList/experimenterList
        serverurl: /service/weather
        icon: /images/GIS-TL_qitaxiaohuoshuan.png
        code: 13
  - app:
        category: java
        application: java
        name: 设备查询
        weichaturl: /pages/index/index
        serverurl: /service/weather
        icon: /images/GIS-TL_zhafa.png
        code: 14
  - app:
        category: java
        application: java
        name: 安全检查
        weichaturl: /pages/index/index
        serverurl: /service/weather
        icon: /images/GIS-TL_mangban.png
        code: 14
  - app:
        category: java
        application: java
        name: Object
        weichaturl: /pages/index/index
        serverurl: /service/weather
        icon: /images/GIS-TL_shensuojie.png
        code: 14
  - app:
        category: java
        application: java
        name: 助理签到
        weichaturl: /pages/index/index
        serverurl: /service/weather
        icon: /images/GIS-TL_sitong.png
        code: 14
developing:
  - app: